-- +goose Up
-- Phone-OTP authentication and basic user management.
-- Secrets (OTP codes, refresh tokens) are stored only as keyed HMAC-SHA256 hashes.
-- IDs are UUIDv7 generated by the application.

CREATE TABLE users (
    id                UUID PRIMARY KEY,
    phone_e164        TEXT        NOT NULL,
    status            TEXT        NOT NULL DEFAULT 'active',
    phone_verified_at TIMESTAMPTZ NOT NULL,
    last_login_at     TIMESTAMPTZ NULL,
    suspended_at      TIMESTAMPTZ NULL,
    suspension_reason TEXT        NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'suspended')),
    CONSTRAINT chk_users_phone_e164 CHECK (phone_e164 ~ '^\+[1-9][0-9]{7,14}$')
);

-- One live account per phone; soft-deleted rows release the number.
CREATE UNIQUE INDEX uq_users_phone_active ON users (phone_e164) WHERE deleted_at IS NULL;

CREATE TABLE user_profiles (
    user_id       UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    display_name  TEXT        NOT NULL DEFAULT '',
    bio           TEXT        NOT NULL DEFAULT '',
    avatar_url    TEXT        NULL,
    avatar_meta   JSONB       NULL,
    date_of_birth DATE        NULL,
    gender        TEXT        NULL,
    home_city     TEXT        NULL,
    country_code  CHAR(2)     NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_profiles_display_name_len CHECK (char_length(display_name) <= 60),
    CONSTRAINT chk_profiles_bio_len CHECK (char_length(bio) <= 500),
    CONSTRAINT chk_profiles_home_city_len CHECK (home_city IS NULL OR char_length(home_city) <= 100),
    CONSTRAINT chk_profiles_gender CHECK (gender IS NULL OR gender IN ('male', 'female', 'non_binary', 'prefer_not_to_say')),
    CONSTRAINT chk_profiles_country_code CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$')
);

-- A session is one signed-in device. Access tokens carry its id (sid claim) so
-- revoking the session invalidates outstanding access tokens immediately.
CREATE TABLE auth_sessions (
    id            UUID PRIMARY KEY,
    user_id       UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_name   TEXT        NULL,
    user_agent    TEXT        NULL,
    ip_address    INET        NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ NOT NULL,
    revoked_at    TIMESTAMPTZ NULL,
    revoke_reason TEXT        NULL,
    CONSTRAINT chk_sessions_revoke_reason CHECK (
        revoke_reason IS NULL
        OR revoke_reason IN ('logout', 'logout_all', 'refresh_reuse', 'suspended', 'admin')
    ),
    CONSTRAINT chk_sessions_revoked_pair CHECK ((revoked_at IS NULL) = (revoke_reason IS NULL))
);

CREATE INDEX idx_auth_sessions_user_active ON auth_sessions (user_id) WHERE revoked_at IS NULL;

-- Rotating refresh tokens. Each refresh marks the presented token used and
-- issues a successor; presenting a used token revokes the whole session.
CREATE TABLE refresh_tokens (
    id         UUID PRIMARY KEY,
    session_id UUID        NOT NULL REFERENCES auth_sessions (id) ON DELETE CASCADE,
    token_hash TEXT        NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_session ON refresh_tokens (session_id);
-- At most one unused refresh token per session.
CREATE UNIQUE INDEX uq_refresh_tokens_session_unused ON refresh_tokens (session_id) WHERE used_at IS NULL;

CREATE TABLE otp_challenges (
    id           UUID PRIMARY KEY,
    phone_e164   TEXT        NOT NULL,
    purpose      TEXT        NOT NULL DEFAULT 'login',
    code_hash    TEXT        NOT NULL,
    attempts     INTEGER     NOT NULL DEFAULT 0,
    max_attempts INTEGER     NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    resend_after TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ NULL,
    request_ip   INET        NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_otp_purpose CHECK (purpose IN ('login')),
    CONSTRAINT chk_otp_attempts CHECK (attempts >= 0 AND attempts <= max_attempts),
    CONSTRAINT chk_otp_max_attempts CHECK (max_attempts > 0),
    CONSTRAINT chk_otp_phone_e164 CHECK (phone_e164 ~ '^\+[1-9][0-9]{7,14}$')
);

-- Serves "latest challenge for phone" and the rolling per-phone daily cap.
CREATE INDEX idx_otp_challenges_phone_created ON otp_challenges (phone_e164, purpose, created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS otp_challenges;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS auth_sessions;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;
